#!/usr/bin/env python
# spur.py
# Copyright (C) ContinuumBridge Limited, 2017 - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Peter Claydon
#

def main():
    print("Snappy Spur Starting")
    print("This is snappy-spur, not snappy-spur.py")
    import bridge.manager.cbsupervisor

if __name__ == '__main__':
    main()

