name: sspur # you probably want to 'snapcraft register <name>'
version: '0.2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: ContinuumBridge cbridge with encaptulated Spur App # 79 char long summary
description: |
  The ContinuumBridge cbridge software is a highly flexible IoT gateway. This
  is a snappy version that locks in the Spur (wireless button) bridge-app.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  sspur:
    command: sspur
  conduit:
    command: node
  start:
    command: start

parts:
  sspur:
    plugin: python
    python-version: 'python2'
    source: https://github.com/ContinuumBridge/sspur.git
    #source-tag: v0.1.6
    source-branch: master
  conduit:
    plugin: nodejs
  glue:
    plugin: dump
    source: glue
  bbridge:
    plugin: dump
    source: ./bbridge
    filesets:
      all: bbridge
