name: snappy-spur # you probably want to 'snapcraft register <name>'
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: ContinuumBridge cbridge with encaptulated Spur App # 79 char long summary
description: |
  The ContinuumBridge cbridge software is a highly flexible IoT gateway. This
  is a snappy version that locks in the Spur (wireless button) bridge-app.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  snappy-spur:
    command: bin/snappy_cbridge
  conduit:
    command: node

parts:
  snappy-spur:
    plugin: python
    python-version: 'python2'
    source: https://github.com/ContinuumBridge/cbridge.git
    source-tag: s0.1.0
    source-branch: snappy
  conduit:
    plugin: nodejs
